#pragma once

#include <QMainWindow>
#include "qextserialenumerator.h"
#include "qextserialport.h"

#include "defines.h"
#include "serialmousereader.h"
#include "microsoftreader.h"
#include "mousesysreader.h"
#include "packetparser.h"

namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    Ui::MainWindow *ui;

    //List of serial ports detected at application startup
    QList<QextPortInfo> serialPorts;

    //The port in use by the mouse
    QextSerialPort* mousePort;

    //The reader that parses bytes reported by the port
    SerialMouseReader* reader;

    //The parser which interprets packets generated by the reader
    PacketParser* parser;

    //Updates settings in the parser to match UI
    void updateParserSettings();

    //Starts the reader in the mode deterined in the UI
    void initReader();

private slots:
    void onReadReady();
    void on_ckbMiddleClickEmulation_toggled(bool checked);
    void on_ckbScrollEmulation_toggled(bool checked);
    void on_pbStart_clicked();
    void on_hsScrollSensitivity_sliderMoved(int position);
    void on_ckbSwapAxis_clicked();
    void on_sbXAccel_valueChanged(int arg1);
    void on_sbYAccel_valueChanged(const QString &arg1);
    void on_ckbInvertX_toggled(bool checked);
    void on_ckbInvertY_toggled(bool checked);
};
